### ISSUE TITLE
newExtent should maybe offer a confirm

### ISSUE THREAD

**Issue by pdebruic** [GsDevKit/GsDevKit_home#123]
I used it while shrinking the repository and now have no tranlogs. Oops.

**Comment by dalehenrich** [comment]
The -n option does not remove tranlogs ... it also doesn't restart the 
stone, either ... when you copy a new extent into a stone directory the 
tranlogs are no longer valid and should not be left there ... at best it 
would cause confustion ...

Most of the scripts are meant to be run in batch mode (newExtent is used 
all over the place), so I don't think it's practical to add in a 
confirmation ...

I suppose I could more prominently mention that the tranlogs would be 
removed in the help text?

Dale

**Comment by pdebruic** [comment]
Well I could also not just assume things about how programs run ...  It was one of those  oh &*#%! moments.  


But when I made this issue I thought it'd be possible to make the default ask for a confirmation and add a flag e.g. -f that would be used in scripts to just execute the newExtent command without confirmation.


But like touching a stove I hope I won't make the mistake again ;)

**Comment by dalehenrich** [comment]
Well, I do think that the standard use cases for newExtent are best 
served by deleting the tranlogs:
   1. using a fresh extent from $GEMSTONE/bin
   2. use a snapshot of the current stone without the intent of doing a 
restore (-n
   3. use a snapshot of a completely different stone

... and the -n flag is the moral equivalent of your `-f` ... the stone 
is not automatically restarted because you do have to figure out what 
you want done with the tranlogs before you start the stone if you don't 
delete the tranlos
... if the tranlogs don't match the extent you get an error
... if the tranlogs do match the extent I think the stone will 
automatically load the tranlogs as if restoring

... so if the tranlogs aren't automatically deleted you need to make a 
set of decisions before restarting the stone ..

Dale

**Comment by pdebruic** [comment]
Its not important to me to adopt a confirmation.  I won't likely shoot myself in the foot on this again.  I was able to recover from a hd backup.  


But just  to be clear my point isn't that the extent should be deleted and the tranlogs should be optionally deleted, just that when used improperly like I did it deleted both the extant extent and the tranlogs and in my instance it might have gotten my attention if there was a confirm that said something like:


You are about to delete the extent and all tranlogs for the stone _________. Do you want to continue? [Y/n]



so I'd argue that the -f isn't like the -n and the confirm is only to prevent unintended consequences during interactive use, by novices, because there is no undo and they may not understand the consequences

**Comment by dalehenrich** [comment]
I do understand your desire for a confirm, but I still think that newExtent is one of those powerful commands - it also blows away whatever extent was present which is a pretty major thing all by itself ... I think that confirmations for shell commands are not that useful --- when you run a shell command you don't really expect to have to confirm and when these unexpected confirms comes up I may not notice till the next day ... I've change the help text to mention that tranlogs are removed in the first paragraph, so I think that should be enough to be clear about when the newExtent command will do ...
