### ISSUE TITLE
Seaside3 project should point to Seaside repo

### ISSUE THREAD

**Issue by jbrichau** [GsDevKit/GsDevKit_home#176]
Since Seaside 3.2, the reference repo on https://github.com/SeasideSt/Seaside is also the one for GsDevKit. The current project definition in this repo still references Seaside 3.1

**Comment by dalehenrich** [comment]
Yeah, I've got a little bit of work to do to get Seaside3.2 to work correctly with tODE ... not a lot of work, but I've been to busy with 3.4 and before that tODE itself to clean things up ... I have a long list of undone things at the moment and there's not much I can do --- I appear to be critical path on too many different projects --- moving things to github was supposed to fix that, since that doesn't appear to be the case, it just means I have more work to do before it becomes true

**Comment by jbrichau** [comment]
ah, I was planning on creating a project myself, but if I understand correctly, there's stuff that needs to be done before doing just that.

**Comment by dalehenrich** [comment]
well it is actually two things:
1. I'm curious what you mean by "current project definition in this repo". There is no project entry [here](https://github.com/GsDevKit/GsDevKit_home/tree/master/sys/default/server/projects), so I'm wondering what else you might be looking at ..
2. the things that need to be worked are these two links from the [README](https://github.com/GsDevKit/GsDevKit_home#installation):
  - [Getting started with Seaside](https://github.com/GsDevKit/GsDevKit_home/blob/master/docs/gettingStartedWithSeaside.md#getting-started-with-seaside)
  - [GsDevKit With Seaside Installation Overview](https://github.com/GsDevKit/GsDevKit_seaside31/blob/master/docs/installation/README.md#gsdevkit-with-seaside-installation-overview)

My preference is to deprecate the second set of instructions in favor of the first ... but I seem to recall that when I tried to follow the steps in the first set of instructions, there were problems using Seasdide3.2 ... and I got stalled -- of course that was done over a year ago and things may have changed since then...

**Comment by dalehenrich** [comment]
There are already pre-defined project entries [here]():
  - [Seaside3](https://github.com/GsDevKit/GsDevKit_home/blob/gh-pages/Seaside3.ston) ... this would be the default Seaside project entry
  - [Seaside3.1](https://github.com/GsDevKit/GsDevKit_home/blob/gh-pages/Seaside31.ston) ... explicit access to Seaside3.1
  - [Seaside3.2](https://github.com/GsDevKit/GsDevKit_home/blob/gh-pages/Seaside32.ston) ... explicit access to Seaside3.2

**Comment by jbrichau** [comment]
Dale,

As I followed the instructions on https://github.com/GsDevKit/GsDevKit_home/blob/master/docs/gettingStartedWithSeaside.md I was under the impression I would load the latest Seaside master version. I did not discover the other project definitions for later Seaside versions and, while searching, I had hit a webpage with a project listing where only this project was mentioned for Seaside (cannot find it anymore right now).

**Comment by jbrichau** [comment]
I'm fine with knowing that Seaside32 has an explicit reference to SeasideSt/Seaside repo. Thanks!
