### ISSUE TITLE
createClient -t tode -v Pharo6.0 fails

### ISSUE THREAD

**Issue by PierceNg** [GsDevKit/GsDevKit_home#219]
Fails. Ditto for Pharo 5.0. Partial dump:

>Evaluated -> baseline [BaselineOfMetacello] >> reprimeRegistryIssue197
>...finished baseline
>...RETRY
>...RETRY'Errors in script loaded from /home/pierce/pkg/GsDevKit_home/sys/default/pharo/todeLoad.st'
>MessageNotUnderstood: FileReference>>closed
>FileReference(Object)>>doesNotUnderstand: #closed
>MCMczReader>>zip
>MCMczReader>>parseMember:
>MCMczReader>>loadPackage
>MCMczReader(MCVersionReader)>>package
>MCMczReader(MCVersionReader)>>basicVersion
>MCMczReader(MCVersionReader)>>version

Didn't try Pharo 4.0. Ran successfully for Pharo 3.0.

**Comment by dalehenrich** [comment]
Thanks @PierceNg ... I should have some time in the not too distant future to dig into this ... I have noticed that Pharo5.0 seems to be failing in the FFI code and I'm wondering if anyone else has noticed:) Since it seems to be a fundamental problem --- of course the whole FFI scene could have shifted at some point ... this all worked just fine a year ago:)

**Comment by PierceNg** [comment]
On Fri, Dec 07, 2018 at 11:00:53PM +0000, Dale Henrichs wrote:
> Thanks @PierceNg ... I should have some time in the not too distant
> future to dig into this ... 

Looking at the error, an MCMczReader instance sent #closed to a
FileReference, which DNU'ed. Between Pharo 3 and later versions, the
object that MCMzReader messaged changed from something that understood
#closed to a FileReference. Should not be too difficult to fix.

> I have noticed that Pharo5.0 seems to be
> failing in the FFI code and I'm wondering if anyone else has noticed:)
> Since it seems to be a fundamental problem --- of course the whole FFI
> scene could have shifted at some point ... this all worked just fine a
> year ago:)

Yes there was a major change in FFI in Pharo 5. Pharo 4's FFI was called
NativeBoost. This was replaced by UFFI in Pharo 5.

**Comment by dalehenrich** [comment]
thanks for the info @PierceNg! `createClient` was working for Pharo5.0 and then Pharo05.0 changed at some point and the createClietn code stopped working ... at first I imagined it was probably a short term hiccup, but it seems that whatever caused the failures has become a permanent part of Pharo5.0 ...

As of 3 months ago, [the travis ci tests for GsDevKit_home and Pharo6.0 were passing](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/431280597) and at that time [the Pharo5.0 tests were not passing](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/431280596).

5 months ago [the Pharo6.1 tests were failing](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/392334199)

9 months ago [the Pharo5.0 tests were passing](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/357206854)

It's been more than 9 months since I've changed the client code, so I will need to try to understand what changed in the various versions of Pharo to cuase things to start failing ...

**Comment by dalehenrich** [comment]
@PierceNg with PR #227 I fixed the issue with Pharo5.0 ... and I am currently working on Issue #229 which will add Pharo6.1 (32 bit) and Pharo7.0 (64 bit) support ... do you need Pharo6.0 supported as well ... I imagine that the only real difference between Pharo6.0 and Pharo6.1 is Iceberg in Pharo6.1, so I will include Pharo6.0 support in Issue #229 ... closing this issue in favor of Issue #229

**Comment by PierceNg** [comment]
On Fri, Jan 25, 2019 at 09:14:01AM -0800, Dale Henrichs wrote:
> @PierceNg with PR #227 I fixed the issue with Pharo5.0 ... and I am
> currently working on Issue #229 which will add Pharo6.1 (32 bit) and
> Pharo7.0 (64 bit) support ... do you need Pharo6.0 supported as well
> ... I imagine that the only real difference between Pharo6.0 and
> Pharo6.1 is Iceberg in Pharo6.1, so I will include Pharo6.0 support in
> Issue #229 ... closing this issue in favor of Issue #229

Thank you, Dale, for fixing this. From Pharo 5 onwards, I'd venture that
supporting the most recent version (so Pharo 7), or at a stretch both
versions 7 and 6.1, is good enough.
