### ISSUE TITLE
Can't find newly created Seaside components

### ISSUE THREAD

**Issue by laszloszolnoki** [GsDevKit/GsDevKit_home#297]
I'm completely new to Smalltalk/Gemstone/Seaside.
I installed stone/tode client with the scripts provided in GsDevKit_home repository's install instructions in the same node on an Ubuntu 18.04.3 LTS VM. (I had to use a full-fledged VM because I couldn't get all things to work neither by using a docker image nor Windows WSL Linux)
I installed Seaside via:
project install --url=http://gsdevkit.github.io/GsDevKit_home/Seaside32.ston
then issued
project load --loads=`#('Welcome' 'Development' 'Zinc Project' 'Examples')` Seaside3
and
mount @/sys/stone/dirs/Seaside3/tode /home seaside
Then loaded the project:
project load --loads=`#('Seaside-GemStone-Adaptors-Zinc')` Seaside3
defined server:
/home/seaside/gemServer --register=seaside --type=zinc --port=1750
started server:
/home/seaside/gemServer --start=seaside
I did everything like I read on the 'Getting started with Seaside' page.

The welcome page showed up but after I had created components (which I could see in the Smalltalk image immediately), couldn't navigate to in the browser. I get a /<app name> not found page.
I checked this with a vanilla Pharo6 image with Seaside3 from both Windows and Linux and it worked fine.
Should you have any clues please share.
Thank you very much.

**Comment by dalehenrich** [comment]
I know that the Windows WSL has had problems running GemStone ... one problem is that they do not support 32 bit executables, but I undertand that there are additional issues with WSL and I don't think we recommend that it be used with GemSTone.

I think that docker images, need some special care as well ... it isn't necessarily a recommended practice to run data bases in docker images, because the disk image isn't persisted (IIRC)... I've never personally tried to solve the docker problem for GsDevkit_home, but there have been a few folks that have experimented with docker and GemStone:
- [jgfoster/DockerForGemStone](https://github.com/jgfoster/DockerForGemStone) 
- [ba-st/docker-gemstone-s](https://github.com/ba-st/docker-gemstone-s)
- [cdavidshaffer/gemstone-docker](https://github.com/cdavidshaffer/gemstone-docker)
- [TerraAustralis/gsDeploymentTools](https://github.com/TerraAustralis/gsDeploymentTools) 

but I'm not sure that any of them have created a docker with GsDevKit_home included, so running and managing the stones is a bit more difficult 

If you just want to run GemStone, then the above solutions might work, otherwise to run GsDevKit_home, you'd have to use a 18.04 vm ...

**Comment by dalehenrich** [comment]
Oh, I see that you are not asking a docker question:) ... 

This sounds like it just might be a  question you should ask on the [Seaside mailing list](http://forum.world.st/Seaside-f1310907.html). One of the Seaside maintainers is using GemStone and Seaside (as well as Pharo and Seaside), so there are folks on that mailing list should be able to help you out ... The `/ not found page` sounds like the components you created were not registered when you created/installed them in GemStone and were obviously registered correctly in Pharo ...

**Comment by laszloszolnoki** [comment]
Thanks for the response,
it isn't really a big deal after all that the Seaside Welcome Page app doesn't behave as intended, I just thought that it may point to some deeper issue.

**Comment by dalehenrich** [comment]
@laszloszolnoki, I appreciate your concern, however, it's not clear from your description what the issue with new components might be, it could be pilot error, it could be something else. Either way, the place to sort that out is on the Seaside mailing list:)
