### ISSUE TITLE
Error parsing some method selectors

### ISSUE THREAD

**Issue by brunobuzzi** [GsDevKit/GsDevKit_home#298]
It seems there is bug in ChangeList>>parseSelector: (or Scanner>>scanMessageParts:) (tested on GS 3.5.1 & 3.5.4).
Try:
```
ChangeList parseSelector:
'myMethodName
    -1 to: 2 do: [:i |].'. 
```
But the following will work ok :
```
ChangeList parseSelector:
'myMethodName
    ||
    -1 to: 2 do: [:i |].'. 
```
So it seems a border case when you have a negative number immediately after the selector. 
The following also will fail:
```
ChangeList parseSelector:
'myMethodName
    -1 '. 
```

The workaround will be add  empty temp definition at the beginning "||" of the method.

**Comment by dalehenrich** [comment]
closed in favor of GsDevKit/GsDevKit#128 ... @brunobuzzi, when you said you would report the bug agains GsDevKit< it hought you meant GsDevKit/GsdevKit :) ... I've been meaning for quite sometime to convert things to use [GsDevKit/GsdevKit](https://github.com/GsDevKit/GsDevKit) instead of [glassdb/glass](https://github.com/glassdb/glass) but the logistics of switch git repositories in mid stream seems to be more trougle thatn it is worth? When Rowan is finally on the scened, I can make the switch ... I assume:)
