### ISSUE TITLE
GS2.5.3+ is packaged as .dmg files on MacOS. Add GsDevKit support for installing these packages

### ISSUE THREAD

**Issue by JupiterJones** [GsDevKit/GsDevKit_home#303]

**Comment by dalehenrich** [comment]
@JupiterJones I tested the fix for unpacking .dmg files and got the follwoing error on a OS X 10.14.6 machine ... the good news is that the .dmg was successfully unpacked and failed the `umount`:
```
[Info] Starting download of GemStone64Bit3.6.0-i386.Darwin.dmg for GemStone  musaeus

[Info] Downloading https://downloads.gemtalksystems.com/pub/GemStone64/3.6.0/GemStone64Bit3.6.0-i386.Darwin.dmg using /usr/bin/curl -O -s -S

[Info] Uncompressing GemStone archive into /musaeus1/users/dhenrich/_home_master/shared/downloads/products/

/musaeus1/users/dhenrich/_home_master/bin/downloadGemStone: line 176: umount: command not found

Error on or near line 165 :: downloadGemStone 3.6.0 :: downloadGemStone 3.6.0

Error on or near line 201 :: createStone gs_360 3.6.0 :: createStone gs_360 3.6.0
```

I suppose the `umount` isn't required, but since you are more experienced on the mac I'll leave this to you ... 

BTW, I do have access to a variety of OSX/Darwin versions, if that would help for testing: 
- OS X 10.15.6 "Catalina" (Darwin 19.6.0)
- OS X 11.2.2 "Big Sur" (Darwin 20.3.0)
- OS X 10.14.6 "Mojave" (Darwin 18.7.0) --- the machine that I ran my test on
- OS X 10.9.5 "Mavericks" (Darwin 13.4.0)
- OSX 10.12.6 "Sierra" (Darwin 16.7.0)
- OS X 11.1 "Big Sur" (Darwin 20.2.0)
- OS X 10.9.x "Mavericks"
- OSX 10.13.2 "High Sierra" (Darwin 17.3.0)

Let me know if there are any additional tests that you think are worth trying ...

Also on the `OS X 10.14.6 "Mojave" (Darwin 18.7.0)` machine I'm having trouble launching the headless pharo - it is hanging... since it has been several years since I've actually worked with a mac, I'm not sure if I've set things up correctly or not ... I'll go reread the docs to see if I've missed something obvious :)

**Comment by dalehenrich** [comment]
FWIW here's more detail on the pharo hang:
```
musaeus:pharo>pwd
/musaeus1/users/dhenrich/_home_master/shared/pharo
musaeus:pharo>./pharo --help
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2021-03-13 11:09:25.637 Pharo[54167:46353409] In void modifyShouldRestoreOnRelaunchCounter(int32_t), _LSSetApplicationInformationItem(_kLSPersistenceSuppressRelaunchAtLoginKey) returned error -600
2021-03-13 11:09:25.691 Pharo[54167:46353411] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
```
looks like the headless pharo is expecting to connect to a window manager? ... the machine I'm using is running as a headless server... I think ... it is in the office but I haven't been in the office for 6 months:)

**Comment by dalehenrich** [comment]
hmmm, at the end of the day, I don't need Pharo running on my OSX machine ... I was hoping that I could use GsDevKit_home to do development and testing on OSX, but I can manually create the stones that I need (3.7.0 and 3.6.0 stones) and once I get superdoit working on OSX, so that you can do do the necesary ... which is my primary goal ... it doesn't really matter that I'm having trouble with pharo :)

If you have an easy answer, then I can use it, but don't spend anymore time on my account and I will close this bug ...

**Comment by dalehenrich** [comment]
[MERGED to master](https://github.com/GsDevKit/GsDevKit_home/pull/306)
